//
//  StudentInformation.swift
//  OnTheMap
//
//  Created by Benny on 1/10/16.
//  Copyright © 2016 Benny Rodriguez. All rights reserved.
//

import Foundation
import MapKit

struct StudentInformation {
    
    var objectId: String // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    var uniqueKey: String // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account (user) id
    var firstName: String // the first name of the student which matches their Udacity profile first name
    var lastName: String // the last name of the student which matches their Udacity profile last name
    var mapString: String? // the location string used for geocoding the student location
    var mediaURL: String? // the URL provided by the student
    var latitude: Double? // the latitude of the student location (ranges from -90 to 90)
    var longitude: Double? // the longitude of the student location (ranges from -180 to 180)
    
    lazy var mapAnnotation: MKPointAnnotation = {
       
        return self.generatePointAnnotationObj();
    }()
    
    init(dictionary: NSDictionary) {
        

        if let firstName = dictionary["firstName"] as? String {
            
            self.firstName = firstName
            
        } else {
            
            self.firstName = ""
        }
        
        if let lastName = dictionary["lastName"] as? String {
            
            self.lastName = lastName
            
        } else {
            
            self.lastName = ""
        }
        
        if let latitude = dictionary["latitude"] as? Double {
            
            self.latitude = latitude // 34.7303688
        }
        
        if let longitude = dictionary["longitude"] as? Double {
            
            self.longitude = longitude // -86.5861037,
        }
        
        if let mapString = dictionary["mapString"] as? String {
            
            self.mapString = mapString // Mountain View, CA
        }
        
        if let mediaURL = dictionary["mediaURL"] as? String {
            
            self.mediaURL = mediaURL
        }
        
        if let objectId = dictionary["objectId"] as? String {
            
            self.objectId = objectId
            
        } else {
            
            self.objectId = ""
        }
        
        if let uniqueKey = dictionary["uniqueKey"] as? String {
            
            self.uniqueKey = uniqueKey
            
        } else {
            
            self.uniqueKey = ""
        }
        
    }
    
    private func generatePointAnnotationObj() -> MKPointAnnotation {
        
        let annotation = MKPointAnnotation()
        
        annotation.coordinate = CLLocationCoordinate2D(latitude: latitude!, longitude: longitude!)
        annotation.title = "\(firstName) \(lastName)"
        annotation.subtitle = mediaURL
        
        return annotation
    }
    
    func fullName() -> String {
        
        return "\(firstName) \(lastName)"
    }
}
